### PR TITLE
Add module-info to the project

### PR DESCRIPTION
**Pull request by Thihup**

### CODE REVIEW

**Comment by Thihup** [comment]
I'm closing as to actually work with modules it is required some changes in how to get the MethodHandle.lookup of the caller

**Comment by forax** [comment]
Hi,
the code that use MapTrait or WithTrait should add "open your_package to com.github.forax.recordutil".

Can you test ?

**Comment by Thihup** [comment]
Hi. I give it a try, but it throws the following exception:

```
Exception in thread "main" java.lang.IllegalAccessError
        at com.github.forax.recordutil@1.0-SNAPSHOT/com.github.forax.recordutil.TraitImpl.teleport(TraitImpl.java:101)
        at com.github.forax.recordutil@1.0-SNAPSHOT/com.github.forax.recordutil.TraitImpl$1.computeValue(TraitImpl.java:85)
        at com.github.forax.recordutil@1.0-SNAPSHOT/com.github.forax.recordutil.TraitImpl$1.computeValue(TraitImpl.java:78)
        at java.base/java.lang.ClassValue.getFromHashMap(ClassValue.java:228)
        at java.base/java.lang.ClassValue.getFromBackup(ClassValue.java:210)
        at java.base/java.lang.ClassValue.get(ClassValue.java:116)
        at com.github.forax.recordutil@1.0-SNAPSHOT/com.github.forax.recordutil.TraitImpl.mapShape(TraitImpl.java:114)
        at com.github.forax.recordutil@1.0-SNAPSHOT/com.github.forax.recordutil.MapTrait.keys(MapTrait.java:371)
        at test@1.0-SNAPSHOT/test.Main.main(Main.java:9)
Caused by: java.lang.IllegalAccessException: module com.github.forax.recordutil does not read module test
        at java.base/java.lang.invoke.MethodHandles.privateLookupIn(MethodHandles.java:255)
        at com.github.forax.recordutil@1.0-SNAPSHOT/com.github.forax.recordutil.TraitImpl.teleport(TraitImpl.java:99)
        ... 8 more
```
module-info.java
```java
open module test {
    exports test;
    requires com.github.forax.recordutil;
}
```
Main.java
```java
package test;

import com.github.forax.recordutil.MapTrait;

public class Main {
    public static void main(String[] args) {
        record Point(int x, int y) implements MapTrait {}
        var p = new Point(10, 20);
        System.out.println(p.keys());
    }
}
```

**Comment by forax** [comment]
Thanks,
re-reading the doc of MethodHandles.privateLookupIn,
"If the caller module M1 differs from the target module M2 then both of the following must be true:
  -  M1 reads M2.
  -  M2 opens the package containing the target class to at least M1.
"

i've forgotten to add the read access, if you pull the last commit, it should work

**Comment by Thihup** [comment]
It worked ;)

**Pull request merged**
